server:
  port: 7100
  max-http-header-size: 10240
  tomcat:
    uri-encoding: utf-8

spring:
  redis:
    host: "localhost"
    password: "Oasis2020"
    database: 0
    port: 6379
    timeout: 60000
  application:
    name: websocket-server
  cloud:
    nacos:
      discovery:
        server-addr: mse-d733b250-p.nacos-ans.mse.aliyuncs.com
        namespace: e47a316d-9466-4c77-ae96-2969d36b69ae
#      config:
#        server-addr: mse-d733b250-p.nacos-ans.mse.aliyuncs.com

logging:
  config: classpath:logback-spring.xml
  path: ./../logs
  level:
    root: INFO
    org.springframework: INFO
    me.yannis.websocket: INFO

rocketmq:
  accessKey: "LTAI4GBU6eMYvYVGF5SxX7Y1"
  secretKey: "BaNyoeI4hBqeo1aAWUKXgKz400n352"
  nameSrvAddr: "http://MQ_INST_1776731713785881_BcWcJltI.mq-internet-access.mq-internet.aliyuncs.com:80"


